'use strict';
define(function (require) {
var Hogan = require('hogan/hogan-2.0.0.amd');
var templates = {};
templates.accountList = new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");if(_.s(_.f("accounts",c,p,1),c,p,0,13,40,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("<tr>");_.b("\n" + i);_.b(_.rp("part",c,p,"    "));_.b("</tr>");_.b("\n");});c.pop();}return _.fl();;});
templates.accountOne = new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");_.b("<td><a class=\"btn btn-xs btn-theme account\" href=\"#/account/");_.b(_.v(_.f("id",c,p,0)));_.b("\" id=\"");_.b(_.v(_.f("id",c,p,0)));_.b("\"><i class=\"glyphicon glyphicon-edit\"></i></a></td>");_.b("\n" + i);_.b("    <td><a  href=\"#/account\" class=\"account\" id=\"");_.b(_.v(_.f("id",c,p,0)));_.b("\">");_.b(_.v(_.f("name",c,p,0)));_.b("</a><span class=\"account-type ");_.b(_.v(_.f("type",c,p,0)));_.b("\" title=\"");_.b(_.v(_.f("type",c,p,0)));_.b("\"></span><a href=\"");_.b(_.v(_.f("link",c,p,0)));_.b("\" target=\"_blank\" class=\"non-button\"><i class=\"glyphicon glyphicon-export\"></i></a></td>");_.b("\n" + i);_.b("    <td class=\"isNumber\">");_.b(_.v(_.f("balance",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("    <td class=\"isNumber hidden-xs hidden-sm\">");_.b(_.v(_.f("confirmed",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("    <td class=\"isNumber\">");_.b(_.v(_.f("remaining",c,p,0)));_.b("</td>");return _.fl();;});
templates.transactionList = new Hogan.Template(function(c,p,i){var _=this;_.b(i=i||"");if(_.s(_.f("transactions",c,p,1),c,p,0,17,387,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("<tr>");_.b("\n" + i);_.b("    <td><a class=\"btn btn-xs btn-theme\"  href=\"#/trans/");_.b(_.v(_.f("id",c,p,0)));_.b("\"><i class=\"glyphicon glyphicon-edit\"></i></a></td>");_.b("\n" + i);_.b("    <td>");_.b(_.v(_.f("date",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("    <td>");_.b(_.v(_.f("type",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("    <td class=\"isNumber\"d>");_.b(_.v(_.f("value",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("    <td><input type=\"checkbox\" class=\"toggleConfirm\" name=\"confirm");_.b(_.v(_.f("id",c,p,0)));_.b("\" id=\"confirm");_.b(_.v(_.f("id",c,p,0)));_.b("\" value=\"true\" /></td>");_.b("\n" + i);_.b("    <td style=\"max-width:200px\">");_.b(_.v(_.f("note",c,p,0)));_.b("</td>");_.b("\n" + i);_.b("</tr>");_.b("\n");});c.pop();}return _.fl();;});
return templates;
});
